"""This module specifies some information about the package."""
PROJECT = 'SDN Serial Controller'
DESCRIPTION = 'An open source implementation of a SDWSN controller'
KEYWORDS = 'SDWSN controller SDN WSN'
AUTHOR = 'Fernando Jurado-Lasso'
EMAIL = 'ffjla@dtu.dk'
LICENSE = 'MIT License'
GITHUB_URL = 'https://github.com/fdojurado/SDWSN-controller'
DOC_URL = 'https://github.com/fdojurado/SDWSN-controller/wiki'
TRACKER_URL = 'https://github.com/fdojurado/SDWSN-controller/issues'
APP = 'serial-controller'
VERSION = '0.1'
